version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./themes/theme:/opt/keycloak/themes
    command:
      [
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
        "-Dkeycloak.profile=preview",
        "start-dev",
        "--spi-theme-static-max-age=-1",
        "--spi-theme-cache-themes=false",
        "--spi-theme-cache-templates=false",
      ]

    env_file:
      - ./env/.env.development
    ports:
      - 8090:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keycloak
  db:
    image: mysql:8.0.29
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./env/.env.development
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 3
    networks:
      - keycloak

volumes:
  mysql_data:
    driver: local

networks:
  keycloak:
    driver: bridge
